### ISSUE TITLE
[BUG] Wrong os type on Windows

### ISSUE THREAD

**Issue by jixiaoyong** [psuzn/multiplatform-paths#36]
Hello, thanks for your awesome job. I found this lib can't run correctly on my Windows 11, it's `hostOs` has been detected as "Linux(arch=X64, version=10.0)" rather than "Windows":

Maybe there is a mistype in the code below:

```
internal fun hostOs(osName: String, archName: String, version: String): Platform.OS {
  val arch = hostArch(archName)
  return when (hostOs(osName)) {
    DesktopOs.Macos -> Platform.OS.MacOs(arch, version)
    DesktopOs.Linux -> Platform.OS.Linux(arch, version)
    DesktopOs.Windows -> Platform.OS.Linux(arch, version) // this should be Platform.OS.Windows
    DesktopOs.Unknown -> Platform.OS.Unknown(arch, version)
  }
}
```

the origin code is here:

https://github.com/psuzn/multiplatform-paths/blob/66f3fedbe19d9a1221b14d1d1fc924913336bf7b/platform-identifier/src/desktopCommonMain/kotlin/me/sujanpoudel/utils/platformIdentifier/os.kt#L43

**Comment by psuzn** [comment]
Thank you for this.

**Comment by psuzn** [comment]
[v0.2.2-beta-1](https://github.com/psuzn/multiplatform-paths/releases/tag/v0.2.2-beta-1) fixes this. It might take an hour or so for this pre-release to propagate to Maven Central.

**Comment by jixiaoyong** [comment]
Thanks a lot, this version(https://github.com/psuzn/multiplatform-paths/releases/tag/v0.2.2-beta-1) works perfectly as expected.

**Comment by psuzn** [comment]
Closing this as [v0.2.2](https://github.com/psuzn/multiplatform-paths/releases/tag/v0.2.2) has been released. 

Again, thank you @jixiaoyong for the catch.
